openapi: 3.0.1
info:
  version: "1.0"
  title: STACKIT Costs API
  termsOfService: "https://stackit.de/en/imprint"
  description: |
    The costs API provides detailed reports on the costs for a customer or project over a certain amount of time
tags:
  - name: service-costs
    description: Costs service
servers:
  - url: "https://api-dev.stackit.cloud"
    description: Development endpoint
    x-stackit-upstream-stage: dev

paths:
  "/costs-service/v1/costs/{customerAccountId}":
    parameters:
      - schema:
          type: string
          format: uuid
        name: customerAccountId
        in: path
        required: true
        description: ID of a customer account
    get:
      summary: Reports for all projects
      tags:
        - service-costs
      responses:
        "200":
          description: OK
      x-stackit-authorization:
        resourceID: customerAccountId
        action: account.controlling.read
  "/costs-service/v1/costs/{customerAccountId}/projects/{projectId}":
    parameters:
      - schema:
          type: string
          format: uuid
        name: customerAccountId
        in: path
        required: true
        description: ID of a customer account
      - schema:
          type: string
          format: uuid
        name: projectId
        in: path
        required: true
        description: ID of a project
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: string
          application/xml:
            schema:
              type: string
      summary: Reports for a certain project
      tags:
        - service-costs
      responses:
        "200":
          description: OK
      x-stackit-authorization:
        resourceID: projectId
        resourceType: project
        action: project.controlling.write
