/*
api-manager-api

STACKIT API Manager API

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// APIManagerServiceRetireRequest struct for APIManagerServiceRetireRequest
type APIManagerServiceRetireRequest struct {
	Metadata *V1Metadata `json:"metadata,omitempty"`
}

// NewAPIManagerServiceRetireRequest instantiates a new APIManagerServiceRetireRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAPIManagerServiceRetireRequest() *APIManagerServiceRetireRequest {
	this := APIManagerServiceRetireRequest{}
	return &this
}

// NewAPIManagerServiceRetireRequestWithDefaults instantiates a new APIManagerServiceRetireRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAPIManagerServiceRetireRequestWithDefaults() *APIManagerServiceRetireRequest {
	this := APIManagerServiceRetireRequest{}
	return &this
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *APIManagerServiceRetireRequest) GetMetadata() V1Metadata {
	if o == nil || o.Metadata == nil {
		var ret V1Metadata
		return ret
	}
	return *o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *APIManagerServiceRetireRequest) GetMetadataOk() (*V1Metadata, bool) {
	if o == nil || o.Metadata == nil {
		return nil, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *APIManagerServiceRetireRequest) HasMetadata() bool {
	if o != nil && o.Metadata != nil {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given V1Metadata and assigns it to the Metadata field.
func (o *APIManagerServiceRetireRequest) SetMetadata(v V1Metadata) {
	o.Metadata = &v
}

func (o APIManagerServiceRetireRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Metadata != nil {
		toSerialize["metadata"] = o.Metadata
	}
	return json.Marshal(toSerialize)
}

type NullableAPIManagerServiceRetireRequest struct {
	value *APIManagerServiceRetireRequest
	isSet bool
}

func (v NullableAPIManagerServiceRetireRequest) Get() *APIManagerServiceRetireRequest {
	return v.value
}

func (v *NullableAPIManagerServiceRetireRequest) Set(val *APIManagerServiceRetireRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAPIManagerServiceRetireRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAPIManagerServiceRetireRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAPIManagerServiceRetireRequest(val *APIManagerServiceRetireRequest) *NullableAPIManagerServiceRetireRequest {
	return &NullableAPIManagerServiceRetireRequest{value: val, isSet: true}
}

func (v NullableAPIManagerServiceRetireRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAPIManagerServiceRetireRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
