/*
STACKIT API Management Service

STACKIT API Manager

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// RetireRequest struct for RetireRequest
type RetireRequest struct {
	ApiVersion *string `json:"apiVersion,omitempty"`
	// Identifier of API to be retired
	Identifier *string `json:"identifier,omitempty"`
	// Project ID for API to be retired
	ProjectId *string `json:"projectId,omitempty"`
}

// NewRetireRequest instantiates a new RetireRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRetireRequest() *RetireRequest {
	this := RetireRequest{}
	return &this
}

// NewRetireRequestWithDefaults instantiates a new RetireRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRetireRequestWithDefaults() *RetireRequest {
	this := RetireRequest{}
	return &this
}

// GetApiVersion returns the ApiVersion field value if set, zero value otherwise.
func (o *RetireRequest) GetApiVersion() string {
	if o == nil || o.ApiVersion == nil {
		var ret string
		return ret
	}
	return *o.ApiVersion
}

// GetApiVersionOk returns a tuple with the ApiVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RetireRequest) GetApiVersionOk() (*string, bool) {
	if o == nil || o.ApiVersion == nil {
		return nil, false
	}
	return o.ApiVersion, true
}

// HasApiVersion returns a boolean if a field has been set.
func (o *RetireRequest) HasApiVersion() bool {
	if o != nil && o.ApiVersion != nil {
		return true
	}

	return false
}

// SetApiVersion gets a reference to the given string and assigns it to the ApiVersion field.
func (o *RetireRequest) SetApiVersion(v string) {
	o.ApiVersion = &v
}

// GetIdentifier returns the Identifier field value if set, zero value otherwise.
func (o *RetireRequest) GetIdentifier() string {
	if o == nil || o.Identifier == nil {
		var ret string
		return ret
	}
	return *o.Identifier
}

// GetIdentifierOk returns a tuple with the Identifier field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RetireRequest) GetIdentifierOk() (*string, bool) {
	if o == nil || o.Identifier == nil {
		return nil, false
	}
	return o.Identifier, true
}

// HasIdentifier returns a boolean if a field has been set.
func (o *RetireRequest) HasIdentifier() bool {
	if o != nil && o.Identifier != nil {
		return true
	}

	return false
}

// SetIdentifier gets a reference to the given string and assigns it to the Identifier field.
func (o *RetireRequest) SetIdentifier(v string) {
	o.Identifier = &v
}

// GetProjectId returns the ProjectId field value if set, zero value otherwise.
func (o *RetireRequest) GetProjectId() string {
	if o == nil || o.ProjectId == nil {
		var ret string
		return ret
	}
	return *o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RetireRequest) GetProjectIdOk() (*string, bool) {
	if o == nil || o.ProjectId == nil {
		return nil, false
	}
	return o.ProjectId, true
}

// HasProjectId returns a boolean if a field has been set.
func (o *RetireRequest) HasProjectId() bool {
	if o != nil && o.ProjectId != nil {
		return true
	}

	return false
}

// SetProjectId gets a reference to the given string and assigns it to the ProjectId field.
func (o *RetireRequest) SetProjectId(v string) {
	o.ProjectId = &v
}

func (o RetireRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.ApiVersion != nil {
		toSerialize["apiVersion"] = o.ApiVersion
	}
	if o.Identifier != nil {
		toSerialize["identifier"] = o.Identifier
	}
	if o.ProjectId != nil {
		toSerialize["projectId"] = o.ProjectId
	}
	return json.Marshal(toSerialize)
}

type NullableRetireRequest struct {
	value *RetireRequest
	isSet bool
}

func (v NullableRetireRequest) Get() *RetireRequest {
	return v.value
}

func (v *NullableRetireRequest) Set(val *RetireRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableRetireRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableRetireRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRetireRequest(val *RetireRequest) *NullableRetireRequest {
	return &NullableRetireRequest{value: val, isSet: true}
}

func (v NullableRetireRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRetireRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
