/*
api-manager-api

STACKIT API Manager API

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// APIManagerServicePublishRequest struct for APIManagerServicePublishRequest
type APIManagerServicePublishRequest struct {
	Metadata *V1Metadata `json:"metadata,omitempty"`
	Spec *PublishRequestSpec `json:"spec,omitempty"`
}

// NewAPIManagerServicePublishRequest instantiates a new APIManagerServicePublishRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAPIManagerServicePublishRequest() *APIManagerServicePublishRequest {
	this := APIManagerServicePublishRequest{}
	return &this
}

// NewAPIManagerServicePublishRequestWithDefaults instantiates a new APIManagerServicePublishRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAPIManagerServicePublishRequestWithDefaults() *APIManagerServicePublishRequest {
	this := APIManagerServicePublishRequest{}
	return &this
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *APIManagerServicePublishRequest) GetMetadata() V1Metadata {
	if o == nil || o.Metadata == nil {
		var ret V1Metadata
		return ret
	}
	return *o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *APIManagerServicePublishRequest) GetMetadataOk() (*V1Metadata, bool) {
	if o == nil || o.Metadata == nil {
		return nil, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *APIManagerServicePublishRequest) HasMetadata() bool {
	if o != nil && o.Metadata != nil {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given V1Metadata and assigns it to the Metadata field.
func (o *APIManagerServicePublishRequest) SetMetadata(v V1Metadata) {
	o.Metadata = &v
}

// GetSpec returns the Spec field value if set, zero value otherwise.
func (o *APIManagerServicePublishRequest) GetSpec() PublishRequestSpec {
	if o == nil || o.Spec == nil {
		var ret PublishRequestSpec
		return ret
	}
	return *o.Spec
}

// GetSpecOk returns a tuple with the Spec field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *APIManagerServicePublishRequest) GetSpecOk() (*PublishRequestSpec, bool) {
	if o == nil || o.Spec == nil {
		return nil, false
	}
	return o.Spec, true
}

// HasSpec returns a boolean if a field has been set.
func (o *APIManagerServicePublishRequest) HasSpec() bool {
	if o != nil && o.Spec != nil {
		return true
	}

	return false
}

// SetSpec gets a reference to the given PublishRequestSpec and assigns it to the Spec field.
func (o *APIManagerServicePublishRequest) SetSpec(v PublishRequestSpec) {
	o.Spec = &v
}

func (o APIManagerServicePublishRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Metadata != nil {
		toSerialize["metadata"] = o.Metadata
	}
	if o.Spec != nil {
		toSerialize["spec"] = o.Spec
	}
	return json.Marshal(toSerialize)
}

type NullableAPIManagerServicePublishRequest struct {
	value *APIManagerServicePublishRequest
	isSet bool
}

func (v NullableAPIManagerServicePublishRequest) Get() *APIManagerServicePublishRequest {
	return v.value
}

func (v *NullableAPIManagerServicePublishRequest) Set(val *APIManagerServicePublishRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAPIManagerServicePublishRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAPIManagerServicePublishRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAPIManagerServicePublishRequest(val *APIManagerServicePublishRequest) *NullableAPIManagerServicePublishRequest {
	return &NullableAPIManagerServicePublishRequest{value: val, isSet: true}
}

func (v NullableAPIManagerServicePublishRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAPIManagerServicePublishRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


