/*
STACKIT API Management Service

STACKIT API Manager

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// PublishResponse OpenAPI specification was published successfully
type PublishResponse struct {
	// URL under which published API is available
	ApiUrl *string `json:"apiUrl,omitempty"`
	// List of specific warnings returned by the API specification linter
	LinterWarnings []string `json:"linterWarnings,omitempty"`
	// Number of warnings returned by the API specification linter
	LinterWarningsCount *string `json:"linterWarningsCount,omitempty"`
	// Indicates whether the PR was created
	PullRequestCreated *bool `json:"pullRequestCreated,omitempty"`
	// URL of the PR which is created with the published specification
	PullRequestUrl *string `json:"pullRequestUrl,omitempty"`
}

// NewPublishResponse instantiates a new PublishResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPublishResponse() *PublishResponse {
	this := PublishResponse{}
	return &this
}

// NewPublishResponseWithDefaults instantiates a new PublishResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPublishResponseWithDefaults() *PublishResponse {
	this := PublishResponse{}
	return &this
}

// GetApiUrl returns the ApiUrl field value if set, zero value otherwise.
func (o *PublishResponse) GetApiUrl() string {
	if o == nil || o.ApiUrl == nil {
		var ret string
		return ret
	}
	return *o.ApiUrl
}

// GetApiUrlOk returns a tuple with the ApiUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PublishResponse) GetApiUrlOk() (*string, bool) {
	if o == nil || o.ApiUrl == nil {
		return nil, false
	}
	return o.ApiUrl, true
}

// HasApiUrl returns a boolean if a field has been set.
func (o *PublishResponse) HasApiUrl() bool {
	if o != nil && o.ApiUrl != nil {
		return true
	}

	return false
}

// SetApiUrl gets a reference to the given string and assigns it to the ApiUrl field.
func (o *PublishResponse) SetApiUrl(v string) {
	o.ApiUrl = &v
}

// GetLinterWarnings returns the LinterWarnings field value if set, zero value otherwise.
func (o *PublishResponse) GetLinterWarnings() []string {
	if o == nil || o.LinterWarnings == nil {
		var ret []string
		return ret
	}
	return o.LinterWarnings
}

// GetLinterWarningsOk returns a tuple with the LinterWarnings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PublishResponse) GetLinterWarningsOk() ([]string, bool) {
	if o == nil || o.LinterWarnings == nil {
		return nil, false
	}
	return o.LinterWarnings, true
}

// HasLinterWarnings returns a boolean if a field has been set.
func (o *PublishResponse) HasLinterWarnings() bool {
	if o != nil && o.LinterWarnings != nil {
		return true
	}

	return false
}

// SetLinterWarnings gets a reference to the given []string and assigns it to the LinterWarnings field.
func (o *PublishResponse) SetLinterWarnings(v []string) {
	o.LinterWarnings = v
}

// GetLinterWarningsCount returns the LinterWarningsCount field value if set, zero value otherwise.
func (o *PublishResponse) GetLinterWarningsCount() string {
	if o == nil || o.LinterWarningsCount == nil {
		var ret string
		return ret
	}
	return *o.LinterWarningsCount
}

// GetLinterWarningsCountOk returns a tuple with the LinterWarningsCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PublishResponse) GetLinterWarningsCountOk() (*string, bool) {
	if o == nil || o.LinterWarningsCount == nil {
		return nil, false
	}
	return o.LinterWarningsCount, true
}

// HasLinterWarningsCount returns a boolean if a field has been set.
func (o *PublishResponse) HasLinterWarningsCount() bool {
	if o != nil && o.LinterWarningsCount != nil {
		return true
	}

	return false
}

// SetLinterWarningsCount gets a reference to the given string and assigns it to the LinterWarningsCount field.
func (o *PublishResponse) SetLinterWarningsCount(v string) {
	o.LinterWarningsCount = &v
}

// GetPullRequestCreated returns the PullRequestCreated field value if set, zero value otherwise.
func (o *PublishResponse) GetPullRequestCreated() bool {
	if o == nil || o.PullRequestCreated == nil {
		var ret bool
		return ret
	}
	return *o.PullRequestCreated
}

// GetPullRequestCreatedOk returns a tuple with the PullRequestCreated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PublishResponse) GetPullRequestCreatedOk() (*bool, bool) {
	if o == nil || o.PullRequestCreated == nil {
		return nil, false
	}
	return o.PullRequestCreated, true
}

// HasPullRequestCreated returns a boolean if a field has been set.
func (o *PublishResponse) HasPullRequestCreated() bool {
	if o != nil && o.PullRequestCreated != nil {
		return true
	}

	return false
}

// SetPullRequestCreated gets a reference to the given bool and assigns it to the PullRequestCreated field.
func (o *PublishResponse) SetPullRequestCreated(v bool) {
	o.PullRequestCreated = &v
}

// GetPullRequestUrl returns the PullRequestUrl field value if set, zero value otherwise.
func (o *PublishResponse) GetPullRequestUrl() string {
	if o == nil || o.PullRequestUrl == nil {
		var ret string
		return ret
	}
	return *o.PullRequestUrl
}

// GetPullRequestUrlOk returns a tuple with the PullRequestUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PublishResponse) GetPullRequestUrlOk() (*string, bool) {
	if o == nil || o.PullRequestUrl == nil {
		return nil, false
	}
	return o.PullRequestUrl, true
}

// HasPullRequestUrl returns a boolean if a field has been set.
func (o *PublishResponse) HasPullRequestUrl() bool {
	if o != nil && o.PullRequestUrl != nil {
		return true
	}

	return false
}

// SetPullRequestUrl gets a reference to the given string and assigns it to the PullRequestUrl field.
func (o *PublishResponse) SetPullRequestUrl(v string) {
	o.PullRequestUrl = &v
}

func (o PublishResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.ApiUrl != nil {
		toSerialize["apiUrl"] = o.ApiUrl
	}
	if o.LinterWarnings != nil {
		toSerialize["linterWarnings"] = o.LinterWarnings
	}
	if o.LinterWarningsCount != nil {
		toSerialize["linterWarningsCount"] = o.LinterWarningsCount
	}
	if o.PullRequestCreated != nil {
		toSerialize["pullRequestCreated"] = o.PullRequestCreated
	}
	if o.PullRequestUrl != nil {
		toSerialize["pullRequestUrl"] = o.PullRequestUrl
	}
	return json.Marshal(toSerialize)
}

type NullablePublishResponse struct {
	value *PublishResponse
	isSet bool
}

func (v NullablePublishResponse) Get() *PublishResponse {
	return v.value
}

func (v *NullablePublishResponse) Set(val *PublishResponse) {
	v.value = val
	v.isSet = true
}

func (v NullablePublishResponse) IsSet() bool {
	return v.isSet
}

func (v *NullablePublishResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePublishResponse(val *PublishResponse) *NullablePublishResponse {
	return &NullablePublishResponse{value: val, isSet: true}
}

func (v NullablePublishResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePublishResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
