openapi: 3.0.1
x-stackit-api:
  type: stackit
x-stackit-scope:
  visibility: private
info:
  version: "1.0"
  title: Dog test API
  termsOfService: "https://stackit.de/en/imprint"
  description: "Math with dogs"
servers:
  - url: "https://mock.api.integration.tst.stackit.cloud"
    description: Targets integration tests Mock service
    x-stackit-stage: dev
tags:
  - name: squares
    description: square of numbers
paths:
  /v1/squares/{num}:
    get:
      description: operation to get square of number
      tags:
        - squares
      parameters:
        - schema:
            type: integer
            format: int32
          name: num
          in: path
          required: true
          description: number to be squared
          example: 123
      operationId: returnSquareOfNumber
      summary: Returns the square of the number
      responses:
        "200":
          description: OK
      x-stackit-upstream:
        path: "/quadrat/{num}"
      x-stackit-authentication:
        disabled: true
      x-stackit-authorization:
        disabled: true
      x-stackit-signer:
        disabled: true
