openapi: 3.0.1
x-stackit-api:
  type: stackit
x-stackit-scope:
  visibility: private
info:
  version: "1.0"
  title: Dog test API
  termsOfService: "http://stackit.de/en/imprint"
  description: "Math with dogs"
servers:
  - url: "https://mock.api.integration.tst.stackit.cloud"
    description: Targets integration tests Mock service
    x-stackit-stage: dev
paths:
  /v1/squares/{numToSquare}:
    get:
      parameters:
        - schema:
            type: integer
            format: int32
          name: numToSquare
          in: path
          required: true
          example: 123
      summary: Returns the square of the number
      responses:
        "200":
          description: OK
      x-stackit-upstream:
        path: "/quadrat/{numToSquare}"
      x-stackit-authentication:
        disabled: true
      x-stackit-authorization:
        disabled: true
      x-stackit-signer:
        disabled: true
